/**
 * Shapes shared by the /n8n workflow library.
 *
 * Two of them cross a network boundary and are therefore contracts, not just
 * types: `CatalogEntry` is what `public/n8n/catalog.json` holds, and
 * `WorkflowDetail` is what each `public/n8n/workflows/<id>.json` holds. Both
 * files are generated by `scripts/build-n8n-catalog.mjs`; changing a field
 * here means regenerating them.
 */

/** How a workflow starts. Ordered from most to least specific. */
export type Trigger = 'Webhook' | 'Scheduled' | 'Chat' | 'Form' | 'App event' | 'Sub-workflow' | 'Manual'

/** Rough size, from the number of real steps. */
export type Complexity = 'Simple' | 'Standard' | 'Advanced'

/**
 * What a node is for. Drives the colour of its block in the diagram, so the
 * shape of a workflow is readable before any label is.
 */
export type NodeKind = 'trigger' | 'ai' | 'logic' | 'data' | 'app' | 'output'

/**
 * One row in the browse index.
 *
 * Deliberately small: there are two thousand of these in one file, and every
 * field costs about 2 kB across the catalog before compression. Anything that
 * can be derived, or that nothing on screen reads, does not belong here.
 */
export interface CatalogEntry {
  /** Source filename without `.json`. Stable, and the detail file's name. */
  id: string
  name: string
  category: string
  trigger: Trigger
  complexity: Complexity
  /** Nodes that do something. Sticky notes are annotations and do not count. */
  steps: number
  /** Services this workflow talks to, most-used first. */
  integrations: string[]
  /** One line from the workflow's own notes, or a generated fallback. */
  summary: string
  /**
   * Present when the summary is the author's own words rather than a
   * generated sentence. The single best signal of a workflow worth reading,
   * which is what the unsearched view is ordered by. Absent rather than
   * `false`, because two thousand `"documented":false` would cost more than
   * the field is worth.
   */
  documented?: 1
  /** Bytes of the original workflow JSON, for the detail view's byte count. */
  bytes: number
}

/** A node as the diagram needs it. */
export interface WorkflowNode {
  name: string
  /** Full n8n type, e.g. `n8n-nodes-base.googleSheets`. */
  type: string
  /** Human label for the type, e.g. `Google Sheets`. */
  label: string
  kind: NodeKind
  /** n8n canvas coordinates, unmodified. */
  x: number
  y: number
  /** Whether this node is disabled in the workflow. */
  disabled?: boolean
}

/** A connection between two nodes, already resolved to node indices. */
export interface WorkflowEdge {
  from: number
  to: number
  /** n8n's connection channel: `main` for data, `ai_*` for agent wiring. */
  channel: string
}

/** A sticky note - the workflow author's own documentation, in markdown. */
export interface WorkflowNote {
  content: string
  x: number
  y: number
  width: number
  height: number
}

/**
 * The detail view's reading of one workflow: what to draw, and what its author
 * wrote on the canvas.
 *
 * Not a file. `public/n8n/workflows/<id>.json` holds the original workflow
 * verbatim - the exact object n8n imports - and this is derived from it in the
 * browser when the panel opens. Publishing both would mean shipping the sticky
 * notes and the node list twice, about 6 MB across the library, and would give
 * the derived copy a chance to drift from the workflow it describes.
 */
export interface WorkflowDetail {
  nodes: WorkflowNode[]
  edges: WorkflowEdge[]
  notes: WorkflowNote[]
}

/** Header written into `catalog.json` next to the entries. */
export interface CatalogFile {
  /**
   * When the catalog was generated. Which corpus it was generated from, and
   * at which ref, is pinned in `scripts/build-n8n-catalog.mjs` and stays
   * there - it is a fact about the build, not about the page.
   */
  source: { generatedAt: string }
  categories: string[]
  entries: CatalogEntry[]
}
