/**
 * Shapes shared by the /public-api directory.
 *
 * `CatalogFile` crosses a network boundary and is therefore a contract rather
 * than just a type: it is exactly what `public/public-api/catalog.json` holds.
 * That file is generated by `scripts/build-public-api-catalog.mjs`, so
 * changing a field here means regenerating it.
 */

/**
 * What you have to present to get a response.
 *
 * Upstream writes this as a free-text cell holding an HTTP mechanism -
 * `apiKey`, `OAuth`, `X-Mashape-Key`, `User-Agent` - or the word "No". Those
 * are collapsed to four buckets here, because the question a reader is asking
 * is "can I call this right now, or do I have to go and sign up", and the
 * exact header name does not change the answer. The original string is kept
 * on the entry as `authLabel` for the ones that do not fit.
 */
export type Auth = 'None' | 'API key' | 'OAuth' | 'Other'

/**
 * Whether a browser can call it directly.
 *
 * Three states, not two, and `Unknown` is the most common one upstream -
 * 992 of 1,773 entries at the time of writing. Rendering that as "No" would
 * be a lie about more than half the directory, so it stays its own value and
 * is presented as unverified rather than as a failure.
 */
export type Cors = 'Yes' | 'No' | 'Unknown'

/**
 * One API in the directory.
 *
 * Deliberately small. There are nearly two thousand of these in one file, and
 * the whole point of a single catalog is that the browse experience never
 * waits on a second request - every field costs about 2 kB across the file
 * before compression.
 */
export interface ApiEntry {
  /** Slug of category + name. Stable across rebuilds, and the share key. */
  id: string
  name: string
  /** One sentence, upstream's own words, trailing full stop removed. */
  description: string
  category: string
  auth: Auth
  /** The upstream cell when `auth` is `Other`, e.g. `X-Mashape-Key`. */
  authLabel?: string
  https: boolean
  cors: Cors
  /** Where the documentation lives. Always absolute, always the link target. */
  url: string
  /** Hostname of `url`, for display and for grouping by provider. */
  host: string
  /**
   * No auth, HTTPS, and CORS confirmed - the three things that have to be
   * true before `fetch()` from a page will work without a proxy.
   *
   * Precomputed rather than derived on the client because it is the default
   * sort's ranking signal and one of the filters, so it would otherwise be
   * recomputed for every entry on every keystroke. Absent rather than
   * `false`, because 1,400 `"ready":false` would cost more than the field is
   * worth.
   */
  ready?: 1
}

/** One category, with the counts the rail needs before any filtering. */
export interface CategoryStat {
  name: string
  total: number
  /** How many of `total` are browser-ready. */
  ready: number
}

/** Header written into `catalog.json` next to the entries. */
export interface CatalogFile {
  /**
   * Which upstream commit this was built from, and when.
   *
   * The ref is recorded in the file rather than only in the build script
   * because the page shows it: a directory of other people's work should say
   * out loud how old its copy is, and link to the exact revision it came
   * from.
   */
  source: {
    repo: string
    ref: string
    generatedAt: string
  }
  categories: CategoryStat[]
  entries: ApiEntry[]
}
